default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: productivity_dashboard
  password: ENV["POSTGRES_PASSWORD"]

development:
  <<: *default
  database: productivity_dashboard_development

test:
  <<: *default
  database: productivity_dashboard_test

production:
  <<: *default
  database: productivity_dashboard_production
  username: productivity_dashboard
  password: <%= ENV['PRODUCTIVITY_DASHBOARD_DATABASE_PASSWORD'] %>
